### ISSUE TITLE
Ember-cli-kanendae prevents ember from building

### ISSUE THREAD

**Issue by maprules1000** [shak/ember-cli-kalendae#11]
After installing with `ember install ember-cli-kalendae` my ember build fails with the following error message:
```
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Attempting to watch missing directory: /Users/userName/projectName/ember/node_modules/kalendae/build
```
I've tried reinstalling and cleaning the cache for yarn but no dice.

**Comment by shak** [comment]
Is it a production build?

**Comment by shak** [comment]
Also, can you provide the ember version your app is using please.

**Comment by shak** [comment]
hi @maprules1000,

I've fixed the issue and just released a new version. Kindly update to latest and the app should build fine.

I apologise for inconvinience, this is my first add-on and I'm still figuring out how to import npm modules correctly (trying to avoid Bower as ember is going to drop support for that soon), hopefully, ember 2.15 would make the process much easier.
